version: "3"
services:
    hub:
      image: selenium/hub:4.1.0
      ports:
        - "4444:4444"
    firefox:
      image: selenium/node-firefox:4.1.0
      shm_size: '1gb'
      deploy:
        replicas: 2
      depends_on:
        - hub
      environment:
        - SE_EVENT_BUS_HOST=hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    login:
      image: egeiper/selenium-testng
      depends_on:
        - firefox
      environment:
        - HUB_HOST=hub
        - MODULE=login.xml
      volumes:
        - ./outputDocker:/usr/share/alpineDirectory/test-output
    navigate:
      image: egeiper/selenium-testng
      depends_on:
        - firefox
      environment:
        - HUB_HOST=hub
        - MODULE=navigate.xml
      volumes:
        - ./outputDocker:/usr/share/alpineDirectory



